### ISSUE TITLE
LoadingController: request error

### ISSUE THREAD

**Issue by arevindh** [thomasjetzinger/openhabit#1]
08-31 03:58:44.636: I/chromium(10128): [INFO:CONSOLE(66)] "LoadingController: request error!
08-31 03:58:44.636: I/chromium(10128): [object Object]", source: file:///android_asset/www/js/loading_controller.js (66)

can you help me with this

**Comment by arevindh** [comment]
seems they removed ws protocol support

**Comment by kirantpatil** [comment]
Hi @arevindh,

Could you please provide the steps to compile and build this project on both android and iOS ?

I have asked same question in issue.

Regards,
Kiran.

**Comment by arevindh** [comment]
@kirantpatil I dropped it because of this issue.
You could use their [api](https://docs.openhab.org/configuration/restdocs.html) to build one using ionic or any similar framework.
